version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
      day: tuesday
      time: "12:00"
    open-pull-requests-limit: 10
    labels:
      - dependabot
